# ~/.config/hypr/hyprtoolkit.conf
# Catppuccin Mocha — Lavender accent

background       = 0xff1e1e2e   # base
base             = 0xff181825   # mantle
text             = 0xffcdd6f4   # text
alternate_base   = 0xff313244   # surface0
bright_text      = 0xffffffff
accent           = 0xffb4befe   # lavender
accent_secondary = 0xffcba6f7   # mauve

# sharp corners, no rounding
rounding_large   = 0
rounding_small   = 0

# font
font_size = 18
font_family = VT323
font_family_ monospace = VT323
icon_theme      = Papirus-Dark
